spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - openid
              - profile
              - email
          facebook:
            client-id: "${FACEBOOK_CLIENT_ID}"
            client-secret: "${FACEBOOK_CLIENT_SECRET}"
            scope:
              - email
              - public_profile




