spring:
  application:
    name: TiraShop
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-jwt.yml
      - classpath:application-security.yml
      - classpath:application-email.yml
logging:
  level:
    org:
      springframework:
        security: TRACE